/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matam
 */
public class ceramicaMonocroma extends javax.swing.JFrame {

    /**
     * Creates new form ceramicaMonocroma
     */
    public ceramicaMonocroma() {
        initComponents();
       mostrar();
       this.setLocationRelativeTo(null);
    }
 


 public void mostrar() {
        Connection conn = null;
        String SQL = "SELECT * FROM ceramicamonocroma " ;
        Statement st;
        CONECTOR con = new CONECTOR();
        conn = con.getConexion();
        DefaultTableModel model = new DefaultTableModel();
        
        // Agrega las columnas que deseas mostrar en la tabla
        model.addColumn("Sitio");
        model.addColumn("Numero_de_bolsa");
        model.addColumn("Unidad");
        model.addColumn("Estructura");
        model.addColumn("Cuarto");
        model.addColumn("E");
        model.addColumn("N");
        model.addColumn("RT");
        model.addColumn("Estrato");
        model.addColumn("Total");
        model.addColumn("Rojo");
        model.addColumn("Negro");
        model.addColumn("Cafe");
        model.addColumn("Burdo_liso");
        model.addColumn("Impresion_una");
        model.addColumn("Peinado");
        model.addColumn("Texturizado");
        model.addColumn("Con_tierra_batida");
        model.addColumn("Otro");
        model.addColumn("Plato");
        model.addColumn("Cajete");
        model.addColumn("Olla");
        model.addColumn("Vaso");
        model.addColumn("Jarra");
        model.addColumn("Molcajete");
        model.addColumn("No_id");
        model.addColumn("Borde");
        model.addColumn("Cuerpo");
        model.addColumn("Asa");
        model.addColumn("Soportes");
        model.addColumn("Registro");
        model.addColumn("Analizo");
        
        tablaCeramicaMonocroma.setModel(model);
        String[] datos = new String[32]; // Ajusta el tamaño al número de columnas en tu tabla

        try {
            st = conn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                for (int i = 1; i <= 32; i++) {
                    datos[i - 1] = rs.getString(i);
                }
                model.addRow(datos);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
 
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCeramicaMonocroma = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCeramicaMonocroma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCeramicaMonocroma);

        jButton1.setText("ELIMINAR");

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1114, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ceramicaMonocroma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ceramicaMonocroma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ceramicaMonocroma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ceramicaMonocroma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ceramicaMonocroma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCeramicaMonocroma;
    // End of variables declaration//GEN-END:variables
}
