/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;


import java.util.HashMap;



public class mostrarSitio extends javax.swing.JFrame {

  private String idDelElementoSeleccionado;
   
  private FramePrincipal framePrincipal;
  private HashMap<String, Integer> topoMap = new HashMap<>();

    public mostrarSitio() {
        initComponents();
        this.setLocationRelativeTo(null);
 FramePrincipal pri=new FramePrincipal();

       
    }


 
  

  
    public void setId(String id) {
        this.idDelElementoSeleccionado = id;
    }
   
    public void setTxtNombreSitio(String nombreSitio) {
       txtNombreSitio.setText(nombreSitio);
    }
 

    public void setCbTipo(String tipo) {
      txtTipo.setText(tipo);
     
    }

    public void setCbRegionesSitios(String regiones) {
       cbRegionesSitios.setText(regiones);
    }

    public void setTxtNombreProyecto(String nombreProyecto) {
       txtNombreProyecto.setText(nombreProyecto);
    }

    public void setTxtFecha(String fecha) {
      txtFecha.setText(fecha);
    }
    public void setTxtPersona(String persona) {
        txtPersona.setText(persona);
    }

   

    public void setTxtLocalidad(String localidad) {
        txtLocalidad.setText(localidad);
    }
     public void setCbMunicipio(String municipio) {
        cbMunicipio.setText(municipio);
    }

    public void setTxtDatum(String datum) {
         txtDatum.setText(datum);
    }

    public void setTxtEste(String este) {
        txtEste.setText(este);
    }

    public void setTxtNorte(String norte) {
        txtNorte.setText(norte);
    }

    public void setTxtAltitud(String altitud) {
        txtAltitud.setText(altitud);
    }

   public void setCbTopo(String topo) {
    
  cbTopo.setText(topo);

}


    public void setCbCronos(String cronos) {
     
        cbCronos.setText(cronos);
    }

 public void setCarta( String ComboBoxCartacarta) {
        ComboBoxCarta.setText(ComboBoxCartacarta);

    }
    public void setTxtDescripcion(String descripcion) {
      txtDescripcion.setText(descripcion);
    }
     public void setExtension(String extension) {
      txtExtension.setText(extension);
      FramePrincipal pri=new FramePrincipal();

    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreSitio = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        jLabel179 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jLabel184 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel185 = new javax.swing.JLabel();
        txtPersona = new javax.swing.JTextField();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        txtLocalidad = new javax.swing.JTextField();
        txtDatum = new javax.swing.JTextField();
        jLabel189 = new javax.swing.JLabel();
        txtEste = new javax.swing.JTextField();
        jLabel190 = new javax.swing.JLabel();
        txtNorte = new javax.swing.JTextField();
        jLabel191 = new javax.swing.JLabel();
        txtAltitud = new javax.swing.JTextField();
        jLabel192 = new javax.swing.JLabel();
        txtExtension = new javax.swing.JTextField();
        jLabel193 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtTipo = new javax.swing.JTextField();
        cbRegionesSitios = new javax.swing.JTextField();
        cbMunicipio = new javax.swing.JTextField();
        cbTopo = new javax.swing.JTextField();
        cbCronos = new javax.swing.JTextField();
        ComboBoxCarta = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JLabel();
        ComboBoxCarta1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(245, 225, 206));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText(" Nombre de Sitio:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel9.setText("DESCRIPCION:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel12.setText("CARTA TOPOGRAFICA:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, -1, -1));
        jPanel3.add(txtNombreSitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 230, -1));

        btnEditar.setText("Editar");
        btnEditar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEditarMouseMoved(evt);
            }
        });
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));
        jPanel3.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, -1));

        jLabel13.setText("Tipo de Sitio: ");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel98.setText("Regiiones Fisiograficas: ");
        jPanel3.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel107.setText("Nombre del Proyecto: ");
        jPanel3.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel3.add(txtNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 200, -1));

        jLabel184.setText("Fecha de registro: ");
        jPanel3.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));
        jPanel3.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, -1));

        jLabel185.setText("Persona que Registró:");
        jPanel3.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));
        jPanel3.add(txtPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 190, -1));

        jLabel186.setText("Municipio:");
        jPanel3.add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel187.setText("Localidad: ");
        jPanel3.add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel188.setText("Datum: ");
        jPanel3.add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));
        jPanel3.add(txtLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 130, -1));
        jPanel3.add(txtDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 130, -1));

        jLabel189.setText("Este: ");
        jPanel3.add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));
        jPanel3.add(txtEste, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 130, -1));

        jLabel190.setText("Norte: ");
        jPanel3.add(jLabel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));
        jPanel3.add(txtNorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 130, -1));

        jLabel191.setText("Altitud:");
        jPanel3.add(jLabel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));
        jPanel3.add(txtAltitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 230, 120, -1));

        jLabel192.setText("Extension en m2:  ");
        jPanel3.add(jLabel192, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));
        jPanel3.add(txtExtension, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 140, -1));

        jLabel193.setText("Topoforma: ");
        jPanel3.add(jLabel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        jLabel10.setText("Cronologia: ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));
        jPanel3.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, -1));
        jPanel3.add(cbRegionesSitios, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 190, -1));
        jPanel3.add(cbMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, 130, -1));
        jPanel3.add(cbTopo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 140, -1));
        jPanel3.add(cbCronos, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 120, 130, -1));
        jPanel3.add(ComboBoxCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 110, -1));
        jPanel3.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jPanel3.add(ComboBoxCarta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseMoved
     //   btnEditar.setBackground(new Color(96,219,164 ));// TODO add your handling code here:
    }//GEN-LAST:event_btnEditarMouseMoved

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
     //   btnEditar.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        btnEditar.setToolTipText("Modificar formulario");
        dispose();
        consultarSitio con=new consultarSitio();
        con.setVisible(true);
        con.mostraSitio();

    }//GEN-LAST:event_btnEditarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
       consultarSitio con=new consultarSitio();
   con.setVisible(true);
  con.mostraSitio();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mostrarSitio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mostrarSitio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mostrarSitio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mostrarSitio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mostrarSitio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ComboBoxCarta;
    private javax.swing.JComboBox<String> ComboBoxCarta1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JTextField cbCronos;
    private javax.swing.JTextField cbMunicipio;
    private javax.swing.JTextField cbRegionesSitios;
    private javax.swing.JTextField cbTopo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAltitud;
    private javax.swing.JTextField txtDatum;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JTextField txtEste;
    private javax.swing.JTextField txtExtension;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtLocalidad;
    private javax.swing.JTextField txtNombreProyecto;
    public javax.swing.JTextField txtNombreSitio;
    private javax.swing.JTextField txtNorte;
    private javax.swing.JTextField txtPersona;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
